apiVersion: platform.company.io/v1alpha1
kind: ClusterEntrypoint
metadata:
  name: namespace-baseline
spec:
  cluster: ocp-dev
  path: infrastructure/gitops-ocp/gitops-namespace-access-platform/platform/namespaces/dev
  managedResources:
    - Namespace
    - ResourceQuota
    - LimitRange
    - NetworkPolicy

