apiVersion: platform.company.io/v1alpha1
kind: ClusterEntrypoint
metadata:
  name: rbac-catalog
spec:
  cluster: ocp-dev
  path: infrastructure/gitops-ocp/ocp-tenant-governance/platform/rbac-catalog
  managedResources:
    - ClusterRole

