apiVersion: access.platform.company.io/v1alpha1
kind: ApplicationAccess
metadata:
  name: dbank-app-05
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  namespaces:
    dev: dbank-app-05-dev
    staging: dbank-app-05-staging
    prod: dbank-app-05-prod
  environments:
    - dev
    - staging
    - prod
  domain: integration
  repository: git@github.com:Rhisko/intelligent-devsecops-framework.git
  owners:
    - ocp-team-integration
  operators:
    - ocp-team-platform
  viewers:
    - ocp-team-security
    - ocp-team-digital-banking
