apiVersion: access.platform.company.io/v1alpha1
kind: ApplicationAccess
metadata:
  name: dbank-app-04
spec:
  namespaces:
    dev: dbank-app-04-dev
    staging: dbank-app-04-staging
    prod: dbank-app-04-prod
  environments:
    - dev
    - staging
    - prod
  domain: risk-management
  repository: git@github.com:Rhisko/intelligent-devsecops-framework.git
  owners:
    - ocp-team-risk
  operators:
    - ocp-team-platform
    - ocp-team-sre
  viewers:
    - ocp-team-security
  auditors:
    - ocp-team-audit
