apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-readonly.yaml
  - namespace-operator.yaml
  - namespace-owner-limited.yaml
  - namespace-deployer.yaml
  - security-auditor.yaml

