apiVersion: v1
kind: Namespace
metadata:
  name: dbank-app-03-staging
  labels:
    app.kubernetes.io/name: dbank-app-03
    app.kubernetes.io/managed-by: argocd
    platform.company.io/managed-by: platform-team
    platform.company.io/application: dbank-app-03
    platform.company.io/environment: staging
    platform.company.io/domain: loan-management

