apiVersion: platform.company.io/v1alpha1
kind: ClusterEntrypoint
metadata:
  name: access-bindings
spec:
  cluster: ocp-dev
  path: infrastructure/gitops-ocp/gitops-namespace-access-platform/platform/access-control/bindings/dev
  managedResources:
    - RoleBinding

