apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbank-app-04-owners
  namespace: dbank-app-04-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ocp-team-risk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-owner-limited
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbank-app-04-operators
  namespace: dbank-app-04-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ocp-team-platform
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ocp-team-sre
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbank-app-04-viewers
  namespace: dbank-app-04-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ocp-team-security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-readonly
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dbank-app-04-auditors
  namespace: dbank-app-04-prod
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: ocp-team-audit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-auditor

