apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-same-namespace.yaml
  - networkpolicy-allow-egress-dns.yaml
  - networkpolicy-allow-frontend-egress-to-dbank-app-03-04-backend.yaml
