apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ocp-team-loan
  labels:
    platform.company.io/managed-by: platform-team
    platform.company.io/domain: loan-management
users:
  - user-loan-01

