apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ocp-team-integration
  labels:
    platform.company.io/managed-by: platform-team
    platform.company.io/domain: integration
users:
  - user-integration-01

