apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ocp-team-platform
  labels:
    platform.company.io/managed-by: platform-team
    platform.company.io/domain: platform
users:
  - user-platform-01

