apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ocp-team-digital-banking
  labels:
    platform.company.io/managed-by: platform-team
    platform.company.io/domain: digital-banking
users:
  - user-dbank-01

