apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: ocp-team-security
  labels:
    platform.company.io/managed-by: platform-team
    platform.company.io/domain: security
users:
  - user-security-01

