apiVersion: platform.company.io/v1alpha1
kind: ClusterEntrypoint
metadata:
  name: rbac-catalog
spec:
  cluster: ocp-prod
  path: infrastructure/gitops-ocp/gitops-namespace-access-platform/platform/rbac-catalog
  managedResources:
    - ClusterRole

