
services:
  jenkins:
    build:
      # context: ..
      dockerfile: jenkins/Dockerfile
      platforms: 
      - linux/amd64
      - linux/arm64
    image: riskoregistry77/jenkins-custom:v1.0.0                               
    container_name: jenkins
    user: "1000:1000"
    ports:
      - "${JENKINS_HTTP_PORT}:8080"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - TRIVY_CACHE_DIR=/var/lib/trivy
      - JAVA_OPTS=-Xms256m -Xmx1024m
      - TZ=${TZ}
    volumes:
      - /Users/risko/Data/tools/jenkins_data/ci-workspace:/ci-workspace
      - /Users/risko/Data/tools/jenkins_data/report-ai-advisoty:/var/jenkins_home/report-ai-advisory
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "0"
    depends_on:
      - sonarqube
    restart: unless-stopped

  sonar-db:
    image: postgres:15-alpine
    container_name: sonar-db
    environment:
      - POSTGRES_USER=${SONARQUBE_JDBC_USERNAME}
      - POSTGRES_PASSWORD=${SONARQUBE_JDBC_PASSWORD}
      - POSTGRES_DB=sonar
      - TZ=${TZ}
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:26.1.0.118079-community
    container_name: sonarqube
    depends_on:
      - sonar-db
    environment:
      - SONAR_JDBC_URL=${SONARQUBE_JDBC_URL}
      - SONAR_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD}
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - TZ=${TZ}
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Xms512m -Xmx${SONARQUBE_JAVA_XMX}
      - SONAR_WEB_JAVAADDITIONALOPTS=-Xms256m -Xmx1024m
    ports:
      - "${SONARQUBE_PORT}:9000"
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
      - sonar_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
  nginx-report:
    image: nginx:stable-alpine
    container_name: nginx-report
    ports:
      - "80:80"
    volumes:
      - /Users/risko/Data/tools/jenkins_data/report-ai-advisory:/usr/share/nginx/html
      - /Users/risko/Data/Pasca_Sarjana/Thesis/Intelligent_DevSecOps_Framework/infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /Users/risko/Data/Pasca_Sarjana/Thesis/Intelligent_DevSecOps_Framework/infrastructure/nginx/generate-index.sh:/generate-index.sh:ro
    command: >
          /bin/sh -c "
          /bin/sh /generate-index.sh &&
          (
            while true; do
              /bin/sh /generate-index.sh;
              sleep 10;
            done
          ) &
          nginx -g 'daemon off;'
          "
    restart: unless-stopped
  # nginx-report:
  #     image: nginx:stable-alpine
  #     container_name: nginx-report
  #     ports:
  #       - "80:80"
  #     volumes:
  #       - /Users/risko/Data/tools/jenkins_data/report-ai-advisoty:/usr/share/nginx/html:ro
  #       - /Users/risko/Data/Pasca_Sarjana/Thesis/Intelligent_DevSecOps_Framework/infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  #     restart: unless-stopped
  # n8n-db:
  #   image: postgres:15-alpine
  #   container_name: n8n-db
  #   environment:
  #     - POSTGRES_USER=${N8N_DB_USER}
  #     - POSTGRES_PASSWORD=${N8N_DB_PASSWORD}
  #     - POSTGRES_DB=${N8N_DB_NAME}
  #     - TZ=${TZ}
  #   volumes:
  #     - n8n_db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U \"$N8N_DB_USER\" -d \"$N8N_DB_NAME\""]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #   restart: unless-stopped

  # n8n:
  #   image: n8nio/n8n:latest
  #   container_name: n8n-app
  #   depends_on:
  #     n8n-db:
  #       condition: service_healthy
  #   environment:
  #     - TZ=${TZ}
  #     - N8N_HOST=${N8N_HOST}
  #     - N8N_PORT=${N8N_PORT}
  #     - N8N_PROTOCOL=http
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
  #     - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}

  #     # Database configuration
  #     - DB_TYPE=postgresdb
  #     - DB_POSTGRESDB_HOST=${N8N_DB_HOST}
  #     - DB_POSTGRESDB_PORT=5432
  #     - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
  #     - DB_POSTGRESDB_USER=${N8N_DB_USER}
  #     - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}

  #     # Webhook URL 
  #     - WEBHOOK_URL=http://${N8N_HOST}:${N8N_PORT}
    
  #   ports:
  #     - "${N8N_PORT}:5678"

  #   volumes:
  #     - n8n_data:/home/node/.n8n

  #   restart: unless-stopped

volumes:
  # ci-workspace:
  jenkins_home:
  sonar_db_data:
  sonar_data:
  sonar_logs:
  sonar_extensions:
  n8n_db_data:
  n8n_data:
