apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../platform/namespaces/prod
  - ../../platform/rbac-catalog
  - ../../platform/access-control/bindings/prod
  - ../../platform/argocd-guardrails/prod
